---
title: "Interactive Map"
output: html_document
date: "2025-11-22"
---

```{r, include=FALSE, echo=FALSE}
library(tidyverse)
library(janitor)
library(lubridate)
library(leaflet)
library(crosstalk)
library(htmltools)
library(DT)

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```


```{r, echo=FALSE}
airplane_df = read_csv("datasets/airplane_crashes_data.csv") |>
  clean_names() |>
  filter(ground != "NULL", aboard != "NULL") |>
  select(-flight_number, -time, -registration)
```

```{r, echo=FALSE}
airplane_df = airplane_df |>
  mutate(
    date = str_trim(date),
    m = as.numeric(sub("/.*", "", date)),
    d = as.numeric(sub(".*/(.*)/.*", "\\1", date)),
    y = as.numeric(sub(".*/(.*)$", "\\1", date)),
    y = ifelse(y < 100, y + 1900, y),
    date_clean = paste(m, d, y, sep = "/"),
    date = mdy(date_clean),
    year = year(date)
  ) |>
  select(-m, -d, -y, -date_clean)
```

```{r, echo=FALSE}
airplane_df = airplane_df |>
  mutate(
    aboard     = as.numeric(aboard),
    fatalities = as.numeric(fatalities),
    ground     = as.numeric(ground),
    operator   = as.factor(operator)
  )
```

```{r, echo=FALSE}
geocoded_locations = read_csv("datasets/geocoded_cache.csv")

df_map <- airplane_df |>
  left_join(geocoded_locations, by = c("location" = "location_clean")) |>
  filter(!is.na(Latitude), !is.na(Longitude))
```

---

## Interactive Filters + Map and Table

```{r, echo=FALSE}
# crosstalk dataset
df_display = df_map |>
  mutate(
    year = as.factor(year),
    operator = as.factor(operator)
  ) |>
  select(year, operator, date, location, fatalities, Latitude, Longitude)

shared = SharedData$new(df_display, group = "crashes")

# Filter Sidebar + Map + Table
bscols(
  widths = c(3, 9),

  # ==== FILTER SIDEBAR ====
  list(
    tags$h3("Filter Crashes"),
    filter_select("year_filter", "Year:", shared, ~year),
    filter_select("op_filter", "Operator:", shared, ~operator),
    filter_slider("fat_filter", "Fatalities:", shared, ~fatalities)
  ),

  # ==== MAP + TABLE AREA ====
  bscols(
    widths = c(7, 5),

    # MAP
    leaflet(shared) |>
      addProviderTiles(providers$CartoDB.Positron) |>
      addCircleMarkers(
        lng = ~Longitude,
        lat = ~Latitude,
        radius = 5,
        fillColor = "red",
        color = "red",
        fillOpacity = 0.6,
        popup = ~paste0(
          "<b>Date:</b> ", date, "<br>",
          "<b>Operator:</b> ", operator, "<br>",
          "<b>Location:</b> ", location, "<br>",
          "<b>Fatalities:</b> ", fatalities
        )
      ) |>
      setView(lng = 0, lat = 20, zoom = 2),

    # TABLE
    DT::datatable(
      shared,
      filter = "top",
      rownames = FALSE,
      options = list(
        pageLength = 4,
        lengthChange = FALSE,
        searching = TRUE,
        autoWidth = TRUE,
        columnDefs = list(
          list(visible = FALSE, targets = c(5, 6))  # hide lat/long
        )
      )
    )
  )
)
```

## Heatmap -- Crash Intensity Heat Layer 

```{r}
leaflet(df_map) |>
  addProviderTiles(providers$CartoDB.Positron) |>
  addMarkers(
    lng = ~Longitude,
    lat = ~Latitude,
    clusterOptions = markerClusterOptions(),
    popup = ~paste("Date:", date, "<br>", "Operator:", operator)
  )

```

```{r}
airplane_df = airplane_df |>
  mutate(
    date = mdy(str_trim(date)),   # fixed
    year = year(date),
    month = month(date),
    operator = as.factor(operator),
    fatalities = as.numeric(fatalities),
    ground = as.numeric(ground),
    aboard = as.numeric(aboard)
  )

```


## Color-coded operator map
```{r}
# Top 5 operators by number of crashes
top_ops = df_map |>
  count(operator, sort = TRUE) |>
  slice(1:5) |>
  pull(operator)

# Filter dataset for ONLY these operators
df_top = df_map |> 
  filter(operator %in% top_ops)

#  palette for the 5 operators
pal = colorFactor(
  palette = rainbow(length(top_ops)),
  domain = top_ops
)

# Leaflet map
leaflet(df_top) |>
  addProviderTiles(providers$CartoDB.Positron) |>
  addCircleMarkers(
    lng = ~Longitude,
    lat = ~Latitude,
    color = ~pal(operator),
    fillOpacity = 0.8,
    radius = 6,
    popup = ~paste0(
      "<b>Operator:</b> ", operator, "<br>",
      "<b>Date:</b> ", format(date, "%Y-%m-%d"), "<br>",
      "<b>Location:</b> ", location
    )
  ) |>
  addLegend(
    position = "bottomright",
    pal = pal,
    values = df_top$operator,
    title = "Top 5 Operators"
  )

```


