---
title: "Airplane Crash Locations Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---



```{r, echo=FALSE}
library(tidyverse)
library(janitor)
library(lubridate)
library(leaflet)
library(shiny)
library(flexdashboard)

# Libraries

```


```{r setup, include=FALSE}
# This code removes all king of error / warning messages 
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = FALSE
)
options(readr.show_col_types = FALSE)

```




```{r, echo=FALSE}
# Loading in the data set:

airplane_df = read_csv("datasets/airplane_crashes_data.csv") |>
  clean_names() |>
  filter(ground != "NULL", aboard != "NULL") |>
  select(-flight_number, -time, -registration)


airplane_df = airplane_df |>
  mutate(
    date = str_trim(date),
    m = as.numeric(sub("/.*", "", date)),
    d = as.numeric(sub(".*/(.*)/.*", "\1", date)),
    y = as.numeric(sub(".*/(.*)$", "\1", date)),
    y = ifelse(y < 100, y + 1900, y),
    date_clean = paste(m, d, y, sep = "/"),
    date = mdy(date_clean),
    year = year(date),
    month = month(date),
    month_name = factor(month(date, label = TRUE, abbr = TRUE),
                        levels = month.abb),
    aboard = as.numeric(aboard),
    fatalities = as.numeric(ground),
    operator = as.factor(operator),
    decade = paste0(floor(year / 10) * 10, "s")
) |>
  select(-m, -d, -y, -date_clean)

# Loading the geocoded cache

geocoded_locations = read_csv("datasets/geocoded_cache.csv")

# Merging all of the coordinates

df_map = airplane_df |>
  left_join(geocoded_locations, by = c("location" = "location_clean")) |>
  filter(!is.na(Latitude), !is.na(Longitude))

```


Global Map - ability to zoom in / zoom out from area of interest:
```{r, echo=FALSE}
renderLeaflet({
  leaflet(df_map) |>
    addProviderTiles(providers$CartoDB.Positron) |>
    addCircleMarkers(
      lng = ~Longitude,
      lat = ~Latitude,
      radius = 5,
      color = "red",
      fillOpacity = 0.5,
      popup = ~paste0(
        "<b>Operator:</b> ", operator, "<br>",
        "<b>Location:</b> ", location, "<br>",
        "<b>Date:</b> ", date
        )
      )
  })

```

```{r, echo=FALSE}
renderUI({
  h3(paste("Crash Locations for Operator:", input$operator_choice))
})

```


```{r, echo=FALSE}
selectizeInput(
  "operator_choice",
  "Choose Operator:",
  choices = sort(unique(df_map$operator)),
  selected = "Aeroflot",
  options = list(maxOptions = 10000)
)


```

```{r, echo=FALSE}
renderLeaflet({
  req(input$operator_choice)

filtered = df_map |>
  filter(operator == input$operator_choice)

leaflet(filtered) |>
  addProviderTiles(providers$CartoDB.Positron) |>
  addCircleMarkers(
    lng = ~Longitude,
    lat = ~Latitude,
    radius = 6,
    color = "blue",
    fillOpacity = 0.6,
    popup = ~paste0(
      "<b>Operator:</b> ", operator, "<br>",
      "<b>Location:</b> ", location, "<br>",
      "<b>Date:</b> ", date
      )
    )
})

```

Airplane Crashes with # of Fatalities: 

```{r}
numericInput(
  "min_fatalities",
  "Show crashes with at least this many fatalities:",
  value = 50,
  min = 0,
  max = max(df_map$fatalities, na.rm = TRUE)
  )

```

```{r}
renderLeaflet({
  req(input$min_fatalities)

filtered <- df_map |>
  filter(!is.na(fatalities), fatalities >= input$min_fatalities)

leaflet(filtered) |>
  addProviderTiles(providers$CartoDB.Positron) |>
  addMarkers(
    lng = ~Longitude,
    lat = ~Latitude,
    clusterOptions = markerClusterOptions(),
    popup = ~paste0(
      "<b>Operator:</b> ", operator, "<br>",
      "<b>Location:</b> ", location, "<br>",
      "<b>Date:</b> ", date, "<br>",
      "<b>Fatalities:</b> ", fatalities
      )
    )
})

```

```{r}
library(tidyverse)
library(janitor)
library(lubridate)
library(leaflet)
library(shiny)
library(flexdashboard)

knitr::opts_chunk$set(
warning = FALSE,
message = FALSE,
echo = FALSE
)
options(readr.show_col_types = FALSE)

```

Page 2
=======================================================================


### Crashes by Year

Row {data-height=150}
-----------------------------------------------------------------------

### Choose a Year
```{r}
# Pre-calc year range
year_min <- min(df_map$year, na.rm = TRUE)
year_max <- max(df_map$year, na.rm = TRUE)

sliderInput(
  "year_choice",
  "Select Year:",
  min = year_min,
  max = year_max,
  value = year_min,
  step = 1,
  sep = ""
)
```

Row {data-height=700}
-----------------------------------------------------------------------

### Map of Crashes for Selected Year
```{r year_map}
renderLeaflet({
  req(input$year_choice)

  filtered <- df_map |>
    filter(year == input$year_choice)

  leaflet(filtered) |>
    addProviderTiles(providers$CartoDB.Positron) |>
    addCircleMarkers(
      lng = ~Longitude,
      lat = ~Latitude,
      radius = 5,
      color = "darkred",
      fillOpacity = 0.6,
      popup = ~paste0(
        "<b>Operator:</b> ", operator, "<br>",
        "<b>Location:</b> ", location, "<br>",
        "<b>Date:</b> ", date
      )
    )
})
```
