---
title: "Airplane Crash Locations Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE, echo=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(janitor)
library(lubridate)
library(leaflet)

knitr::opts_chunk$set(warning = FALSE, message = FALSE)
options(readr.show_col_types = FALSE)
```

######################################################################


######################################################################


```{r, echo=FALSE}
### Load airplane dataset

airplane_df <- read_csv("datasets/airplane_crashes_data.csv") %>%
  clean_names() %>%
  filter(ground != "NULL", aboard != "NULL") %>%
  select(-flight_number, -time, -registration) %>%
  mutate(
    date = mdy(str_trim(date)),
    year = year(date),
    month = month(date),
    aboard = as.numeric(aboard),
    fatalities = as.numeric(fatalities),
    ground = as.numeric(ground),
    operator = as.factor(operator)
  )

### Load geocoded locations

geocoded <- read_csv("datasets/geocoded_cache.csv")

### Merge coordinates

df_map <- airplane_df %>%
left_join(geocoded, by = c("location" = "location_clean")) %>%
filter(!is.na(Latitude), !is.na(Longitude))

### Slider range

year_min <- min(df_map$year, na.rm = TRUE)
year_max <- max(df_map$year, na.rm = TRUE)

### Year slider input

sliderInput(
  "year_choice",
  "Select Year:",
  min = year_min,
  max = year_max,
  value = 1970,   # pick a year with many crashes
  step = 1,
  sep = ""
)


```

######################################################################

######################################################################


🌎 Crash Map by Year
```{r, echo=FALSE}
leafletOutput("map", height = "650px")

```

```{r, echo=FALSE}
output$map <- renderLeaflet({
leaflet() %>%
addProviderTiles(providers$CartoDB.Positron)
})

```

```{r, echo=FALSE}
observe({
req(input$year_choice)

filtered <- df_map %>% filter(year == input$year_choice)

leafletProxy("map", data = filtered) %>%
clearMarkers() %>%
addCircleMarkers(
lng = ~Longitude,
lat = ~Latitude,
radius = 5,
color = "red",
fillOpacity = 0.5,
popup = ~paste0(
"<b>Operator:</b> ", operator, "<br>",
"<b>Location:</b> ", location, "<br>",
"<b>Date:</b> ", date
)
)
})

```

