---
title: "Airplane Crashes - Visualizaed Data with Pinned Locations"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
runtime: shiny
---


```{r, echo=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(janitor)
library(lubridate)
library(leaflet)

knitr::opts_chunk$set(
warning = FALSE,
message = FALSE,
echo = FALSE
)
options(readr.show_col_types = FALSE)

```

```{r}
# Load airplane dataset

airplane_df = read_csv("datasets/airplane_crashes_data.csv") |>
  clean_names() |>
  filter(ground != "NULL", aboard != "NULL") |>

# keep fatalities column

select(-flight_number, -time, -registration)

# Parse dates + create features

airplane_df <- airplane_df |>
  mutate(
    date       = mdy(str_trim(date)),
    year       = year(date),
    month      = month(date),
    month_name = factor(month(date, label = TRUE, abbr = TRUE),
                        levels = month.abb),
    aboard     = as.numeric(aboard),
    fatalities = as.numeric(fatalities),
    operator   = as.factor(operator),
    decade     = paste0(floor(year / 10) * 10, "s")
    )

# Load geocoded cache

geocoded_locations <- read_csv("datasets/geocoded_cache.csv")

# Merge coordinates

df_map = airplane_df |>
  left_join(geocoded_locations, by = c("location" = "location_clean")) |>
  filter(!is.na(Latitude), !is.na(Longitude))

# Pre-calc ranges for inputs

year_min <- min(df_map$year, na.rm = TRUE)
year_max <- max(df_map$year, na.rm = TRUE)

fatal_max <- max(df_map$fatalities, na.rm = TRUE)

```

=======================================================================

-----------------------------------------------------------------------

### 🌎 Global Crash Map

```{r}
renderLeaflet({
  leaflet(df_map) |>
    addProviderTiles(providers$CartoDB.Positron) |>
    addCircleMarkers(
      lng = ~Longitude,
      lat = ~Latitude,
      radius = 5,
      color = "red",
      fillOpacity = 0.5,
      popup = ~paste0(
        "<b>Operator:</b> ", operator, "<br>",
        "<b>Location:</b> ", location, "<br>",
        "<b>Date:</b> ", date
      )
    )
})
``` 



## Operator Filter

```{r}
selectizeInput(
  "operator_choice",
  "Choose Operator:",
  choices  = sort(unique(df_map$operator)),
  selected = "Aeroflot",
  options  = list(maxOptions = 10000)
  )

```




### Crash Locations for Selected Operator

```{r}
renderLeaflet({
  req(input$operator_choice)

filtered = df_map |>
  filter(operator == input$operator_choice)

leaflet(filtered) |>
  addProviderTiles(providers$CartoDB.Positron) |>
  addCircleMarkers(
  lng = ~Longitude,
  lat = ~Latitude,
  radius = 6,
  color = "blue",
  fillOpacity = 0.6,
  popup = ~paste0(
    "<b>Operator:</b> ", operator, "<br>",
    "<b>Location:</b> ", location, "<br>",
    "<b>Date:</b> ", date
    )
  )
})

```

### Crashes by Minimum Fatalities

```{r}
numericInput(
  "min_fatalities",
  "Show crashes with at least this many fatalities:",
  value = 50,
  min   = 0,
  max   = fatal_max
  )

```


```{r}
renderLeaflet({
  req(input$min_fatalities)

filtered = df_map |>
  filter(!is.na(fatalities), fatalities >= input$min_fatalities)

leaflet(filtered) |>
  addProviderTiles(providers$CartoDB.Positron) |>
  addMarkers(
    lng = ~Longitude,
    lat = ~Latitude,
    clusterOptions = markerClusterOptions(),
    popup = ~paste0(
      "<b>Operator:</b> ", operator, "<br>",
      "<b>Location:</b> ", location, "<br>",
      "<b>Date:</b> ", date, "<br>",
      "<b>Fatalities:</b> ", fatalities
      )
    )
})


```



```{r}
sliderInput(
  "year_choice",
  "Select Year:",
  min   = year_min,
  max   = year_max,
  value = year_min,
  step  = 1,
  sep   = ""
  )

```



-----------------------------------------------------------------------

### Map of Crashes for Selected Year



```{r}
renderLeaflet({
  req(input$year_choice)

filtered = df_map |>
  filter(year == input$year_choice)

leaflet(filtered) |>
  addProviderTiles(providers$CartoDB.Positron) |>
  addCircleMarkers(
    lng = ~Longitude,
    lat = ~Latitude,
    radius = 5,
    color = "darkred",
    fillOpacity = 0.6,
    popup = ~paste0(
      "<b>Operator:</b> ", operator, "<br>",
      "<b>Location:</b> ", location, "<br>",
      "<b>Date:</b> ", date
      )
    )
})

```

```{r}
rsconnect::deployDoc("ShinyDashboard2.Rmd")
```




